FROM docker.io/rust:1.85.0-alpine AS bot_builder

RUN apk update \
    && apk add --no-cache --purge libc-dev openssl-dev openssl-libs-static pkgconfig

WORKDIR /work

COPY . .

RUN --mount=type=cache,target=/usr/local/cargo/registry cargo fetch
RUN --mount=type=cache,target=/usr/local/cargo/registry --mount=type=cache,target=/work/target cargo build --release && cp /work/target/release/telegram_sync_bot /work/telegram_sync_bot

########################################

FROM docker.io/alpine:latest AS bot

WORKDIR /app

RUN apk update \
    && apk add --no-cache --purge bash tzdata

COPY --from=bot_builder /work/telegram_sync_bot /app

STOPSIGNAL SIGINT

ENTRYPOINT ["/app/telegram_sync_bot"]

CMD ["--help"]
